server :
  port : 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring :
  application :
    name : apigateway
  cloud :
    gateway:
      routes:
        - id : user
          uri: lb://user/
          predicates :
            - Path=/user/**

        - id: theme
          uri: lb://theme/
          predicates:
            - Path=/theme/**

        - id: feed
          uri: lb://feed/
          predicates:
            - Path=/feed/**


